services:
  - type: web
    name: plataforma-kyc1
    runtime: python-3.12
    buildCommand: pip install --no-cache-dir -r requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.1
      - key: PYTHONUNBUFFERED
        value: "1"
